apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::726917344898:role/UdacityFlaskDeployCBKubectlRole
       username: build
       groups:
         - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-09-03T16:48:59Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "7887"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: f366ef11-5c4f-443e-ad1d-e37ef47616a2